language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
install: true
script: "./gradlew clean build jacocoTestReport"
after_success:
  - bash <(curl -s https://codecov.io/bash)